export const list = [
    {
        id: 1,
        name: "xyz",
        title: "xyz",
        location: "xyz",
        salary: 100,
        user_name: "xyz",
        company_name: "xyz",
        contact: "SE",
    },
    {
        id: 2,
        name: "xyz",
        title: "xyz",
        location: "xyz",
        salary: 100,
        user_name: "xyz",
        company_name: "xyz",
        contact: "SE",
    },
    {
        id: 3,
        name: "xyz",
        title: "xyz",
        location: "xyz",
        salary: 100,
        user_name: "xyz",
        company_name: "xyz",
        contact: "SE",
    },
    {
        id: 4,
        name: "xyz",
        title: "xyz",
        location: "xyz",
        salary: 100,
        user_name: "xyz",
        company_name: "xyz",
        contact: "SE",
    },
    {
        id: 5,
        name: "xyz",
        title: "xyz",
        location: "xyz",
        salary: 100,
        user_name: "xyz",
        company_name: "xyz",
        contact: "SE",
    },
    {
        id: 6,
        name: "xyz",
        title: "xyz",
        location: "xyz",
        salary: 100,
        user_name: "xyz",
        company_name: "xyz",
        contact: "SE",
    },
];
